name: gps_tracking_env
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - aom=3.6.0
  - arrow-cpp=21.0.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - catalogue=2.0.10
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.3.2
  - click=8.3.0
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.5
  - contourpy=1.3.1
  - cuda-cudart=12.4.127
  - cuda-cuobjdump=12.9.82
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvcc=12.4.131
  - cuda-nvdisasm=12.9.88
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - cudnn=9.14.0.64
  - cycler=0.11.0
  - cymem=2.0.6
  - cyrus-sasl=2.1.28
  - cython-blis=0.7.9
  - dav1d=1.2.1
  - dill=0.4.0
  - exceptiongroup=1.2.0
  - expat=2.7.1
  - faiss-gpu=1.9.0
  - fastapi=0.116.1
  - ffmpeg=4.2.2
  - filelock=3.17.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - iniconfig=2.1.0
  - intel-openmp=2023.0.0
  - jinja2=3.1.6
  - jpeg=9f
  - kiwisolver=1.4.8
  - lame=3.100
  - langcodes=3.4.1
  - language-data=1.3.0
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcudnn=9.14.0.64
  - libcudnn-dev=9.14.0.64
  - libcufft=11.2.1.3
  - libcufile=1.14.1.1
  - libcups=2.4.2
  - libcurand=10.3.10.19
  - libcurl=8.15.0
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libdrm=2.4.124
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libfaiss=1.9.0
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libllvm19=19.1.7
  - libmlir19=19.1.7
  - libnghttp2=1.57.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.9.82
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.20.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - libzlib=1.3.1
  - lit=20.1.8
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - magma=2.7.1
  - marisa-trie=0.7.7
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - mdurl=0.1.2
  - mesalib=25.1.5
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multiprocess=0.70.15
  - murmurhash=1.0.7
  - mysql-common=9.3.0
  - mysql-libs=9.3.0
  - nccl=2.28.3
  - ncurses=6.5
  - nettle=3.7.3
  - networkx=3.4.2
  - nomkl=3.0
  - numexpr=2.11.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - ocl-icd=2.3.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.0.18
  - opentelemetry-api=1.37.0
  - orc=2.2.0
  - packaging=25.0
  - pandas=2.3.3
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - pluggy=1.5.0
  - preshed=3.0.6
  - pthread-stubs=0.3
  - pyarrow=21.0.0
  - pycparser=2.23
  - pydantic=2.11.9
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pyparsing=3.2.0
  - pyqt=6.9.1
  - pyqt6-sip=13.10.2
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python-xxhash=3.0.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qtbase=6.9.2
  - qtdeclarative=6.9.2
  - qtsvg=6.9.2
  - qttools=6.9.2
  - qtwayland=6.9.2
  - qtwebchannel=6.9.2
  - qtwebsockets=6.9.2
  - re2=2024.07.02
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - rich=13.9.4
  - s2n=1.5.14
  - setuptools=80.9.0
  - shellingham=1.5.4
  - sip=6.12.0
  - six=1.17.0
  - sleef=3.5.1
  - smart_open=6.4.0
  - snappy=1.2.1
  - spacy=3.7.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - srsly=2.4.3
  - starlette=0.47.3
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - thinc=8.2.2
  - tk=8.6.15
  - tomli=2.2.1
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - triton=3.1.0
  - typer=0.9.4
  - typing-extensions=4.15.0
  - typing-inspection=0.4.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvicorn=0.37.0
  - wasabi=1.1.3
  - wayland=1.24.0
  - weasel=0.3.4
  - wheel=0.45.1
  - x264=1!157.20191217
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - accelerate==1.10.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.0
      - aiosignal==1.4.0
      - anyio==4.11.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - beautifulsoup4==4.14.2
      - bert-score==0.3.13
      - cbor==1.0.0
      - datasets==4.2.0
      - einops==0.8.1
      - flagembedding==1.3.5
      - frozenlist==1.8.0
      - hf-xet==1.1.10
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - idna==3.10
      - ijson==3.4.0.post0
      - inscriptis==2.6.0
      - ir-datasets==0.5.11
      - joblib==1.5.2
      - lxml==6.0.2
      - lz4==4.4.4
      - multidict==6.7.0
      - peft==0.5.0
      - pexpect==4.9.0
      - propcache==0.4.1
      - protobuf==6.32.1
      - psutil==7.1.0
      - pt-core-news-sm==3.8.0
      - ptyprocess==0.7.0
      - rank-bm25==0.2.2
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sentence-transformers==5.1.1
      - sentencepiece==0.2.1
      - sniffio==1.3.1
      - soupsieve==2.8
      - sympy==1.13.1
      - threadpoolctl==3.6.0
      - tokenizers==0.20.3
      - transformers==4.45.2
      - trec-car-tools==2.6
      - unlzw3==0.2.3
      - warc3-wet==0.2.5
      - warc3-wet-clueweb09==0.2.5
      - yarl==1.22.0
      - zlib-state==0.1.10